- name: install mesosphere keys
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=E56151BF

- name: add mesosphere repo
  apt_repository: repo="deb http://repos.mesosphere.com/ubuntu trusty main"

- name: install software-properties-common
  apt: name=software-properties-common

- name: select oracle license for java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections

- name: see oracle license for java
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- name: add java repo
  shell: add-apt-repository ppa:webupd8team/java

- name: install java8
  apt: name=oracle-java8-installer update_cache=yes

- name: set oracle java8 as default
  apt: name=oracle-java8-set-default

- name: install mesos and marathon
  apt: name={{ item }}
  with_items:
    - mesos 
    - marathon


- name: stop services
  service: name={{ item }} state=stopped
  with_items:
    - marathon
    - mesos-slave
    - mesos-master
    - zookeeper
  when: clean is defined and clean

- name: clear data dirs
  file: path={{ item }} state=absent
  with_items:
    - /var/lib/mesos
    - /var/lib/zookeeper
  when: clean is defined and clean

- name: create data dirs
  file: path={{ item }} state=directory mode=0777
  with_items:
    - /var/lib/mesos
    - /var/lib/zookeeper
  when: clean is defined and clean

- name: delete marathon docker tasks
  shell: docker ps -a | grep mesos- | cut -f1 -d ' '
  ignore_errors: yes
  when: clean is defined and clean


- name: start zookeeper
  service: name=zookeeper state=restarted


- name: set zookeeper for mesos
  copy: dest=/etc/mesos/zk content="zk://{{ ansible_eth1.ipv4.address }}:2181/mesos"

- name: set mesos quorum size
  copy: dest=/etc/mesos-master/quorum content=1

- name: set mesos hostname
  copy: dest=/etc/mesos-master/hostname content="{{ ansible_eth1.ipv4.address }}"

- name: set mesos ip
  copy: dest=/etc/mesos-master/ip content="{{ ansible_eth1.ipv4.address }}"

- name: set mesos work dir
  copy: dest=/etc/mesos-master/work_dir content="/var/lib/mesos"

- name: disable mesos hostname lookup
  copy: dest=/etc/mesos-master/hostname_lookup content="false"

- name: start mesos-master service
  service: name=mesos-master state=restarted


- name: create marthon conf dir
  file: path=/etc/marathon/conf state=directory

- name: set marathon hostname
  copy: dest=/etc/marathon/conf/hostname content="{{ ansible_eth1.ipv4.address }}"

- name: set marathon master
  copy: dest=/etc/marathon/conf/master content="zk://{{ ansible_eth1.ipv4.address }}:2181/mesos"

- name: set marathon zk
  copy: dest=/etc/marathon/conf/zk content="zk://{{ ansible_eth1.ipv4.address }}:2181/marathon"

- name: set marathon event stream
  copy: dest=/etc/marathon/conf/event_subscriber content="http_callback"

- name: start marathon
  service: name=marathon state=restarted


- name: set mesos agent hostname
  copy: dest=/etc/mesos-slave/hostname content="{{ ansible_eth1.ipv4.address }}"

- name: disable mesos agent hostname lookup
  copy: dest=/etc/mesos-slave/hostname_lookup content="false"

- name: setup conteinerizers
  copy: dest=/etc/mesos-slave/containerizers content="docker"

- name: start mesos agent
  service: name=mesos-slave state=restarted
